{% set version = "0.20.1" %}

package:
  name: azure-mgmt-resource
  version: {{ version }}

source:
  fn: azure-resource-{{ version }}.zip
  url: https://pypi.io/packages/source/a/azure-mgmt-resource/azure-mgmt-resource-{{ version }}.zip
  md5: d90bfc9fa4cc09d765e75627cd642505
  
build:
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .
  number: 1

requirements:
  host:
    - pip
    - python
    - setuptools
    - azure-mgmt-common
  run:
    - python
    - azure-mgmt-common

test:
  imports:
    - azure
    - azure.mgmt
    - azure.mgmt.resource
  commands:
    - python -m unittest discover -p "test_*.py"

about:
  home: https://github.com/Azure/azure-sdk-for-python
  license: Apache-2.0
  summary: 'Microsoft Azure Resource Management Client Library for Python'

extra:
  recipe-maintainers:
    - ivoflipse
    - Korijn
    - Maxyme
