{% set version = "23.1.0" %}
{% set name = "azure-mgmt-resource" %}
{% set sha256 = "fecc3fe1685dd6a27a56e033becccc798464af5be25f55138539cef49d876028" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.zip
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.8
    - setuptools
    - pip
  run:
    - isodate >=0.6.1
    - python >=3.8
    - azure-common >=1.1
    - azure-mgmt-core >=1.3.2

test:
  files:
    - ./tests/
  imports:
    - azure
    - azure.mgmt
    - azure.mgmt.resource
  commands:
    - python -m unittest discover -p "test_*.py"

about:
  home: https://github.com/Azure/azure-sdk-for-python/tree/master/sdk/resources/azure-mgmt-resource
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Microsoft Azure Resource Management Client Library for Python

extra:
  recipe-maintainers:
    - Maxyme
    - dhirschfeld
