{% set version = "23.0.1" %}
{% set name = "azure-mgmt-resource" %}
{% set sha256 = "c2ba6cfd99df95f55f36eadc4245e3dc713257302a1fd0277756d94bd8cb28e0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.zip
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.zip
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.7
    - setuptools
    - pip
  run:
    - isodate <1.0.0,>=0.6.1
    - python >=3.7
    - azure-common >=1.1,<2.dev0
    - azure-mgmt-core >=1.3.2,<2.0.0
    - msrest >=0.7.1

test:
  imports:
    - azure
    - azure.mgmt
    - azure.mgmt.resource
  commands:
    - python -m unittest discover -p "test_*.py"

about:
  home: https://github.com/Azure/azure-sdk-for-python/tree/master/sdk/resources/azure-mgmt-resource
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Microsoft Azure Resource Management Client Library for Python

extra:
  recipe-maintainers:
    - Maxyme
    - dhirschfeld
