{% set version = "23.4.0" %}
{% set name = "azure-mgmt-resource" %}
{% set sha256 = "7cc0909184bd01439e245f5f2e20945a3668d45a6774e1f008227bb33a733d16" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.zip
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name | replace('-', '_') }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - typing_extensions >=4.6.0
    - isodate >=0.6.1
    - python >={{ python_min }}
    - azure-common >=1.1
    - azure-mgmt-core >=1.5.0

test:
  requires:
    - python {{ python_min }}
  imports:
    - azure
    - azure.mgmt
    - azure.mgmt.resource
  commands:
    - python -m unittest discover -p "test_*.py"

about:
  home: https://github.com/Azure/azure-sdk-for-python/tree/master/sdk/resources/azure-mgmt-resource
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Microsoft Azure Resource Management Client Library for Python

extra:
  recipe-maintainers:
    - janjagusch
    - Maxyme
    - dhirschfeld
