{% set version = "21.2.0" %}
{% set name = "azure-mgmt-resource" %}
{% set sha256 = "bf8a5de6c4dab5efc7f0d18d0f57165dee5231ea52d23d10d82e447b8c2a1a54" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.zip
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.zip
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.6
    - setuptools
    - pip
  run:
    - python >=3.6
    - azure-common >=1.1,<2.0.0
    - azure-mgmt-core >=1.3.0,<2.0.0
    - msrest >=0.6.21

test:
  imports:
    - azure
    - azure.mgmt
    - azure.mgmt.resource
  commands:
    - python -m unittest discover -p "test_*.py"

about:
  home: https://github.com/Azure/azure-sdk-for-python/tree/master/sdk/resources/azure-mgmt-resource
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Microsoft Azure Resource Management Client Library for Python

extra:
  recipe-maintainers:
    - Maxyme
    - dhirschfeld
